### ISSUE TITLE
Pytorch run out of memory

### ISSUE THREAD

**Issue by kuddai** [CuriousAI/mean-teacher#2]
Hi, thanks that you keep pushing semi-supervised ML forward!

I have recently tried pytorch version and apparently my gpu capacity is not enough (6GB). 
I had issues with tensorflow as well but I have already seen that older version of tensorflow may help.

Which brings two suggestions:
- Can you please dockernize your environment so it is easier to reproduce your results?
- Can you add MNIST example. I know it is boring but it will most likely run even on single gpu?

**Comment by tarvaina** [comment]
Yeah, the default hyperparameters on PyTorch have been optimized for Titan X, which has 12 GB. The memory usage should scale nearly linearly in terms of minibatch size. Try `--labeled-batch-size 31 --batch-size 64` as command line parameters to the main.py. If you still run out of memory, try even lower values. You can debug memory usage with e.g. `nvidia-smi` command line tool.

The other suggestions are good, although I am fairly busy at the moment. Pull requests are welcome. :-)
