### ISSUE TITLE
How to unpack training.msgpack and show the training logs?

### ISSUE THREAD

**Issue by lindameiguo** [CuriousAI/mean-teacher#21]
Thanks for your inspiring idea and the corresponding code.

I have run the cifar10 experiments in your code on the AWS cloud.
After i trained the network, the data logs were saved in the cloud.  Then I downloaded the results files, such as,  training.msgpack, but i don't know how to unpack it  to show the training logs.

I have google and searched at stackoverflow. But i still have not find a way to show the logs.

Would you please show me how to unpack the .msgpack file and show the logs?

Thanks.

**Comment by tarvaina** [comment]
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_msgpack.html

**Comment by lindameiguo** [comment]
@tarvaina 
Thank you for the response!
I have found the problem in 'run_context.py'. The compress was set as ‘None’. So i cannot open it. Thank you.
`    def save(self):
        df = self._as_dataframe()
        df.to_msgpack(self.log_file_path, compress='None') `
