### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by LokLu** [CuriousAI/mean-teacher#27]
May I know the version you were using?
The code is not compatible with latest pytorch. Thank yoU!

**Comment by tarvaina** [comment]
Yeah, this was written in 2017 before PyTorch merged variables and tensors. I must have used PyTorch 0.2.0 but I guess 0.3.1 would work too. Sorry for not documenting this.

**Comment by tarvaina** [comment]
Hi, I tested it out and pytorch 0.3.1 works but 0.2.0 doesn't. I must have updated the code to 0.3.1 at some point.

**Comment by LokLu** [comment]
Cool, I will start will 0.3.1 then. Thanks!

**Comment by LokLu** [comment]
0.3.1 works. But from the first iteration, I came across with this loss explosion problem.
I use the original source code with 8 GPUs. Do you any suggestions?

Epoch: [0][0/7207]	Time 59.704 (59.704)	Data 11.010 (11.010)	Class 3.5564 (3.5564)	Cons 0.0247 (0.0247)	Prec@1 0.000 (0.000)	Prec@5 0.000 (0.000)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/scratch/project/pytorch/experiments/imagenet_valid.py", line 82, in <module>
    run(**run_params)
  File "/scratch/project/pytorch/experiments/imagenet_valid.py", line 77, in run
    main.main(context)
  File "/scratch/project/pytorch/main.py", line 104, in main
    train(train_loader, model, ema_model, optimizer, epoch, training_log)
  File "/scratch/project/pytorch/main.py", line 270, in train
    assert not (np.isnan(loss.data[0]) or loss.data[0] > 1e5), 'Loss explosion: {}'.format(loss.data[0])
AssertionError: Loss explosion: 160967.515625

**Comment by LokLu** [comment]
I move following question to a previous issue

**Comment by jessica-santos** [comment]
Hi, the code will be update for a new version of pytorch? 

I'm trying to do this by my own, but I'm new to pytorch and finding some issues. After changing the `.data` to `item`, I try to run the code but receive `RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM`
