### ISSUE TITLE
ImageNet instructions 

### ISSUE THREAD

**Issue by xinmei9322** [CuriousAI/mean-teacher#3]
Hi, thanks for the great work!
I am wondering whether you could upload the instruction to reproduce the ImageNet results. It seems the data preparation for ImageNet is missing. Thanks.

**Comment by tarvaina** [comment]
Thanks for reminding me. The code uses the default torchvision directory structure. See the instructions here: https://github.com/facebook/fb.resnet.torch/blob/master/INSTALL.md#download-the-imagenet-dataset . The code assumes the data resides at `data-local/images/ilsvrc2012/`.

Please let me know if you have any trouble getting it working.

**Comment by xinmei9322** [comment]
Thanks @tarvaina ! It works.
