### ISSUE TITLE
ZCA preprocessing

### ISSUE THREAD

**Issue by vikasverma1077** [CuriousAI/mean-teacher#30]
I can not find where is ZCA preprocessing being applied to CIFAR10 data in pytorch implementation. Am I missing something?

**Comment by tarvaina** [comment]
It’s not. The PyTorch and Tensorflow implementations differ in details. The PyTorch implementation aims to be close to whatever shakeshake resnet did, and Tensorflow close to Pi model.

**Comment by vikasverma1077** [comment]
thanks!
