### ISSUE TITLE
Finally, which one should I take, teacher or student?

### ISSUE THREAD

**Issue by Lilac-wgk** [CuriousAI/mean-teacher#57]
Hi, I am very impressed with your research.

It may seem like a stupid, but I'm wondering what should I use the model for validating.
I'm confusing with some knowledge distillation (KD) methodologies, which use the terms, teacher and student model.
At first I thought those have different meaning (i.e., the word teacher in mean teacher and KD).
However, I'm wondering why the EMA model (teacher model) has better performance than the student model, which is supervised-learned with ground truths. (and the [slide](https://github.com/CuriousAI/mean-teacher/blob/546348ff863c998c26be4339021425df973b4a36/nips_2017_slides.pdf) also tells that the teacher model leads the student model.)
Indeed, the experiments results show that the teacher model has better performances than the students.

1) How can I approach that the EMA-weighted model has better performance than the student model?
2) So, is it correct that the teacher model is using at the final system?

Thanks for reading.

**Comment by tarvaina** [comment]
The teacher is usually as good as or better than the student, so you should
use the teacher.

**Comment by Lilac-wgk** [comment]
Thanks a lot :)
